name: sexy-landing CI/CD

on:
  push:
    branches:
      - staging
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: |
            - recursive: true

      - name: "Build"
        run: pnpm build

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

  deploy-staging:
    if: github.ref == 'refs/heads/staging'
    runs-on:
      - self-hosted
      - staging

    needs: build

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: dist

      - name: show IP
        run: |
          ip add

      - name: show pwd
        run: |
          pwd

      - name: Deploy to staging
        run: |
          sudo rm -rf /var/www/staging/*
          sudo cp -r /home/user/actions-runner/_work/sexyai-landing-page/sexyai-landing-page/* /var/www/staging/

  deploy-production:
    if: github.ref == 'refs/heads/main'
    runs-on:
      - self-hosted
      - production
    needs: build

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: dist

      - name: show IP
        run: |
          ip add

      - name: show pwd
        run: |
          pwd

      - name: Deploy to production
        run: |
          sudo rm -rf /var/www/production/*
          sudo cp -r /home/user/actions-runner/_work/sexyai-landing-page/sexyai-landing-page/. /var/www/production/
